In [1]:
from typing import List, Tuple, Dict
from utils import *
import numpy as np
import heapq
import random
import json

from simulator.simulator import Simulator
from objects.point import Point, get_random_point
from objects.order import Order
from objects.courier import Courier
from objects.active_route import ActiveRoute
from objects.gamble_triple import GambleTriple
from objects.utils import *

In [2]:
from dispatch.dispatch import Dispatch
from tqdm import tqdm
sim = Simulator()
dsp = Dispatch() 

In [33]:
# sim = Simulator()
# sim.Next([])
# sim.Next([(0, 0)])
# state = sim.GetState()

# ass = [(state.orders[o_idx].id, state.couriers[c_idx].id) for o_idx, c_idx in dsp(state)]

[(1, 18), (2, 16), (3, 12)]

In [3]:
from networks.scoring_v1 import ScoringNet, ScoringInterface
net = ScoringNet(
    mode='default',
    # point_encoder=point_encoder,
    n_layers=2,
    d_model=512,
    n_head=4,
    dim_ff=512,
    point_enc_dim=64,
    number_enc_dim=8,
    device='cpu'
)

model = ScoringInterface(net)
model.load_weights('pretrained_models/assignment_cloning_model_v2')


In [5]:
state = sim.GetState()
model.encode_input([state], 0)

torch.Size([20, 512])


In [1]:
try:
    x = 5 / 0
except:
    x = 2
x

2

In [3]:
import torch
torch.ones((5, 1), dtype=torch.bool)

tensor([[True],
        [True],
        [True],
        [True],
        [True]])

In [3]:
from networks.utils import create_mask
a = create_mask([5, 6, 4], None, True)

In [4]:
a

tensor([[ True, False, False, False, False,  True],
        [ True, False, False, False, False, False],
        [ True, False, False, False,  True,  True]])

In [14]:
torch.zeros_like(a, dtype=torch.float).masked_fill_(a, float("-inf"))

tensor([[0., -inf, -inf],
        [0., 0., 0.],
        [0., 0., -inf]])

In [15]:
from torch.nn.utils.rnn import pad_sequence
pad_sequence([[1], [1, 2], [1, 2, 3]])

TypeError: expected Tensor as element 0 in argument 0, but got list

In [17]:
import torch
t = torch.nn.TransformerDecoderLayer(
                    d_model=8, 
                    nhead=2, 
                    dim_feedforward=4, 
                    batch_first=True,
                )

In [25]:
a = torch.randn((2, 3, 8))
b = torch.randn((2, 5, 8))

a_mask = torch.ones((2, 3), dtype=torch.bool)
b_mask = torch.zeros((2, 5), dtype=torch.bool)

In [26]:
t(a, b, tgt_key_padding_mask=a_mask, memory_key_padding_mask=b_mask)

tensor([[[nan, nan, nan, nan, nan, nan, nan, nan],
         [nan, nan, nan, nan, nan, nan, nan, nan],
         [nan, nan, nan, nan, nan, nan, nan, nan]],

        [[nan, nan, nan, nan, nan, nan, nan, nan],
         [nan, nan, nan, nan, nan, nan, nan, nan],
         [nan, nan, nan, nan, nan, nan, nan, nan]]],
       grad_fn=<NativeLayerNormBackward0>)

In [1]:
from simulator.item_generators import CourierGenerator
from simulator.timer import Timer
from objects.point import Point

In [2]:
corner_bounds = (Point(0, 0), Point(10, 10))
t = Timer()
g = CourierGenerator(corner_bounds, t, 10)